name: CI pipeline

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: copy repo
        uses: actions/checkout@v7

      - name: set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: install dependencies
        run: pip install -r ./requirements-dev.txt
      
      - name: lint with ruff
        run: ruff check .

      - name: run tests
        run: pytest -v

      - name: log in to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: compute image tags
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ vars.DOCKERHUB_USERNAME }}/url-shortener
          flavor: latest=false
          tags: |
            type=sha,prefix=
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}

      - name: build and push docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          